// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apgumxuibchusxgstugq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZ3VteHVpYmNodXN4Z3N0dWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2Mzc4NDYsImV4cCI6MjA1NDIxMzg0Nn0.A1Ms16TG1Joi1J5UfU-FjfYZOSSLlzmDl-nNJSLMUyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);